version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server/data:/usr/src/app/data
      - ./public:/usr/src/app/../public:ro
    restart: unless-stopped
  php-backend:
    build: ./php-backend
    ports:
      - "8080:80"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - php-data:/var/www/html/data
    restart: unless-stopped
volumes:
  php-data:
